#!/bin/bash

function handle_error () {
    rc=$1
    err_message=$2

    if [ "0" != "$rc" ]; then
        echo $err_message
        exit $rc
    fi
}

function print_output () {

  echo
  echo "Project is at $DJANGO_HOMEDIR/$DJANGO_PROJ_NAME"
  echo "App is at $DJANGO_HOMEDIR/$DJANGO_PROJ_NAME/$DJANGO_APP_NAME"
  echo
  echo "Important paths for customization"
  echo "  * $DJANGO_HOMEDIR/$DJANGO_PROJ_NAME/templates"
  echo "  * $DJANGO_HOMEDIR/$DJANGO_PROJ_NAME/static"
  echo "  * $DJANGO_HOMEDIR/$DJANGO_PROJ_NAME/$DJANGO_PROJ_NAME/settings.py"
  echo "  * $DJANGO_HOMEDIR/$DJANGO_PROJ_NAME/$DJANGO_APP_NAME/views.py"
  echo "  * $DJANGO_HOMEDIR/$DJANGO_PROJ_NAME/$DJANGO_APP_NAME/models.py"
  echo "  * $DJANGO_HOMEDIR/$DJANGO_PROJ_NAME/$DJANGO_APP_NAME/urls.py"
  echo
  echo "You can now start the application with:"
  echo "  sudo su - $DJANGO_USERNAME python3 -c \"$DJANGO_HOMEDIR/$DJANGO_PROJ_NAME/manage.py runserver\""
  echo
  echo "The following URLs will be available:"
  echo "  * App URL:   http://127.0.0.1:8000/$DJANGO_APP_NAME"
  echo "  * Admin URL: http://127.0.0.1:8000/admin"
  echo
  echo "To make these URLS available in your browser you can simply forward them with:"
  echo "  ssh -L 8000:127.0.0.1:8000 USERNAME@REMOTEIP"
  echo
  echo "You can remove all Django related configuration with:"
  echo "  sudo userdel -r $DJANGO_USERNAME"
  echo "and restart the configuration process, if necessary."
  echo
  echo "You can pack the application with:"
  echo "  sudo tar -C $DJANGO_HOMEDIR/ --exclude=\"*__pycache__*\" --exclude=\"*db.sqlite3*\" -zcf /tmp/$DJANGO_PROJ_NAME.tar.gz $DJANGO_PROJ_NAME"
  echo

}

